version: '3.9'
services:
  test-db:
    container_name: fastapi_test_postgres
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DB_USER_TEST}", "-d", "${DB_NAME_TEST}" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - fastapi_project_network

  test-api:
    container_name: fastapi_test_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "pytest"
    ports:
      - "8000:8000"
    environment:
      MODE: "TEST"
    networks:
      - fastapi_project_network

networks:
  fastapi_project_network:
    name: "fastapi_project_network"