version: '3.9'
services:
  test-db:
    container_name: fastapi_test_postgres
    image: postgres:15.1-alpine
    env_file:
      - .env.tests
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - fastapi_test_network

  test-api:
    container_name: fastapi_test_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.tests
    entrypoint: >
      sh -c "pytest ."
    ports:
      - "8000:8000"
    environment:
      MODE: "TEST"
    networks:
      - fastapi_test_network

  test-cache:
    container_name: fastapi_test_cache
    image: redis:latest
    env_file:
      - .env.tests
    ports:
      - "6379:6379"
    networks:
      - fastapi_test_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  fastapi_test_network:
    name: "fastapi_test_network"
