version: '3.9'
services:
  test-db:
    container_name: fastapi_test_postgres
    image: postgres:15.1-alpine
    env_file:
      - .test.env
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - fastapi_project_network

  test-api:
    container_name: fastapi_test_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .test.env
    entrypoint: >
      sh -c "pytest -a"
    ports:
      - "8000:8000"
    networks:
      - fastapi_project_network

networks:
  fastapi_project_network:
    name: "fastapi_project_network"